### ISSUE TITLE
Please add a license file and some screen shots

### ISSUE THREAD

**Issue by unixorn** [Domanowska/zshSailorMoonThemes#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Finally, consider making separate repos for each theme - with zsh frameworks, it's generally a lot easier for someone to add a plugin/theme as `github_username/reponame` and let the framework find the plugin file than it is for them to add a plugin from a sub directory.

Thanks!

**Comment by Domanowska** [comment]
Hello! I'm honored!

I have now added screenshots to the readme, along with some installation instructions, plus the license.

I would prefer to keep the themes all in one repo since there are 9 of them and they're related, it also seems the frameworks still work if you include the path to the theme file (as seen in the installation section) but I might split them out if there are any issues in the future.

Thank you!
